[project]
name = "dqn-mujoco-gym"
version = "0.1.0"
requires-python = ">=3.12.12"
dependencies = [
    "absl-py",
    "cloudpickle",
    "contourpy",
    "cycler",
    "decorator",
    "etils",
    "farama-notifications",
    "filelock",
    "fonttools",
    "fsspec",
    "glfw",
    "grpcio",
    "gymnasium",
    "imageio",
    "imageio-ffmpeg",
    "importlib-resources",
    "jinja2",
    "kiwisolver",
    "markdown",
    "markupsafe",
    "matplotlib",
    "moviepy",
    "mpmath",
    "mujoco",
    "networkx",
    "numpy",
    "opencv-python",
    "packaging",
    "pandas",
    "pillow",
    "proglog",
    "protobuf",
    "pyopengl",
    "pyparsing",
    "python-dateutil",
    "python-dotenv",
    "pyyaml",
    "seaborn",
    "setuptools",
    "six",
    "sympy",
    "tensorboard",
    "tensorboard-data-server",
    "torch",
    "tqdm",
    "triton",
    "typing-extensions",
    "werkzeug",
    "zipp",
]

[project.optional-dependencies]
cuda = [
    "cuda-bindings",
    "cuda-pathfinder",
    "nvidia-cublas-cu12",
    "nvidia-cuda-cupti-cu12",
    "nvidia-cuda-nvrtc-cu12",
    "nvidia-cuda-runtime-cu12",
    "nvidia-cudnn-cu12",
    "nvidia-cufft-cu12",
    "nvidia-cufile-cu12",
    "nvidia-curand-cu12",
    "nvidia-cusolver-cu12",
    "nvidia-cusparse-cu12",
    "nvidia-cusparselt-cu12",
    "nvidia-nccl-cu12",
    "nvidia-nvjitlink-cu12",
    "nvidia-nvshmem-cu12",
    "nvidia-nvtx-cu12",
]
