seed: 0
device: "gpu"   # "cpu" si no tienes
# device: "cpu"   # "cpu" si no tienes

env:
  env_id: "Walker2d-v5"
  frame_stack: 4
  action_repeat: 1
  time_limit: 1000

  obs_h: 40
  obs_w: 40

  grayscale: false

  
  action_prototypes:

  # 0) noop
  - [ 0.0,  0.0,  0.0,  0.0,  0.0,  0.0]

  # hip
  - [+0, +0, +0, +1, +0, +0]
  - [+0, +0, +0, -1, +0, +0]
  - [+1, +0, +0, +0, +0, +0]
  - [-1, +0, +0, +0, +0, +0]

  # knee
  - [+0, +0, +0, +0, +1, +0]
  - [+0, +0, +0, +0, -1, +0]
  - [+0, +1, +0, +0, +0, +0]
  - [+0, -1, +0, +0, +0, +0]

  # ankle
  - [+0, +0, +0, +0, +0, +1]
  - [+0, +0, +0, +0, +0, -1]
  - [+0, +0, +1, +0, +0, +0]
  - [+0, +0, -1, +0, +0, +0]

  # tobillo + rodilla
  - [+0, +0, +0, +0, +1, -1]   # lean-forward correction (moderate)
  - [+0, +0, +0, +0, -1, +1]   # lean-back correction (strong)
  - [+0, +1, -1, +0, +0, +0]   # lean-forward correction (moderate)
  - [+0, -1, +1, +0, +0, +0]   # lean-back correction (strong)









# train:
#   total_steps: 800000
#   learning_starts: 20000
#   train_freq: 4
#   batch_size: 32
#   buffer_size: 200000
#   gamma: 0.99
#   lr: 1.0e-4
#   target_update_freq: 8000
#   grad_clip_norm: 10.0

train:
  total_steps: 20_000_000
  # total_steps: 100_000
  # total_steps: 80000
  learning_starts: 2_000
  train_freq: 4
  batch_size: 32
  buffer_size: 200_000
  gamma: 0.99
  lr: 1.0e-4
  target_update_freq: 8000
  grad_clip_norm: 10.0
  visualiztion: True

exploration:
  eps_start: 1.0
  eps_end: 0.05
  eps_decay_steps: 300000

eval:
  # every_steps: 49999
  # every_steps: 19_999
  every_steps: 200_000
  episodes: 5

logging:
  render_every: 10
  run_dir: "runs"
  ckpt_dir: "checkpoints"
  log_every: 200_000

stabilizer:
  initial_intensity: 0.01 #10.5
  decay: 0.1
  ref_height: 0.95