seed: 0
# device: "gpu"   # "cpu" si no tienes
device: "cpu"   # "cpu" si no tienes

env:
  env_id: "Walker2d-v5"
  frame_stack: 4
  action_repeat: 4
  time_limit: 1000

  
  # Acciones discretas (prototipos) -> lista de vectores en [-1,1] del tamaño de action_dim (continuous)
  # Ajusta esto según el entorno (action_dim lo puedes imprimir con env.action_space.shape)
  action_prototypes:

  # 0) noop
  - [ 0.0,  0.0,  0.0,  0.0,  0.0,  0.0]

  # 1-4) micro acciones por articulación (exploración barata)
  - [ 0.2,  0.0,  0.0,  0.2,  0.0,  0.0]   # hips small +
  - [-0.2,  0.0,  0.0, -0.2,  0.0,  0.0]   # hips small -
  - [ 0.0,  0.2,  0.0,  0.0,  0.2,  0.0]   # knees small +
  - [ 0.0, -0.2,  0.0,  0.0, -0.2,  0.0]   # knees small -

  # 5-8) tobillos: muy útiles para estabilidad
  - [ 0.0,  0.0,  0.25, 0.0,  0.0,  0.25]  # ankles small +
  - [ 0.0,  0.0, -0.25, 0.0,  0.0, -0.25]  # ankles small -
  - [ 0.0,  0.0,  0.35, 0.0,  0.0, -0.35]  # ankle split (rollover)
  - [ 0.0,  0.0, -0.35, 0.0,  0.0,  0.35]  # ankle split opposite

  # 9-12) corrección de torso (anti-fall)
  # idea: si el torso cae hacia atrás, normalmente ayuda:
  # - meter cadera para "traer" el torso encima del apoyo
  # - usar tobillo para no colapsar
  - [ 0.45, 0.10, -0.20, 0.45, 0.10, -0.20]  # lean-forward correction (moderate)
  - [ 0.70, 0.15, -0.30, 0.70, 0.15, -0.30]  # lean-forward correction (strong)
  - [-0.35,-0.10, 0.20, -0.35,-0.10, 0.20]   # lean-back correction (moderate)
  - [-0.55,-0.15, 0.30, -0.55,-0.15, 0.30]   # lean-back correction (strong)

  # 13-16) gait en dos fases (derecha avanza / izquierda avanza)
  # fase A: derecha swing (thigh/leg/foot) + izquierda stance (más rígida)
  - [-0.55,  0.85, -0.25,  0.25, -0.35,  0.10]  # gait A (R swing / L stance)
  - [-0.75,  1.00, -0.35,  0.35, -0.45,  0.15]  # gait A strong
  # fase B: izquierda swing + derecha stance (simétrica)
  - [ 0.25, -0.35,  0.10, -0.55,  0.85, -0.25]  # gait B (L swing / R stance)
  - [ 0.35, -0.45,  0.15, -0.75,  1.00, -0.35]  # gait B strong



# train:
#   total_steps: 800000
#   learning_starts: 20000
#   train_freq: 4
#   batch_size: 32
#   buffer_size: 200000
#   gamma: 0.99
#   lr: 1.0e-4
#   target_update_freq: 8000
#   grad_clip_norm: 10.0

train:
  # total_steps: 20_000_000
  total_steps: 800
  learning_starts: 20_000
  train_freq: 4
  batch_size: 32
  buffer_size: 200_000
  gamma: 0.99
  lr: 1.0e-4
  target_update_freq: 8000
  grad_clip_norm: 10.0

exploration:
  eps_start: 1.0
  eps_end: 0.05
  eps_decay_steps: 300000

eval:
  every_steps: 300
  # every_steps: 200_000
  episodes: 5

logging:
  render_every: 10
  run_dir: "runs"
  ckpt_dir: "checkpoints"
  log_every: 200000

stabilizer:
  initial_intensity: 0.0 #10.5
  decay: 0.1
  ref_height: 0.95