seed: 0
device: "gpu"   # "cpu" si no tienes
# device: "cpu"   # "cpu" si no tienes

env:
  env_id: "Walker2d-v5"
  frame_stack: 4
  action_repeat: 1
  time_limit: 1000

  obs_h: 54
  obs_w: 54

  grayscale: false

  action_prototypes:

  # 0) noop
  - [+0, +0, +0, +0, +0, +0]

  # hip
  - [+0, +0, +0, +1, +0, +0]
  - [+0, +0, +0, -1, +0, +0]
  - [+1, +0, +0, +0, +0, +0]
  - [-1, +0, +0, +0, +0, +0]

  # knee
  - [+0, +0, +0, +0, +1, +0]
  - [+0, +0, +0, +0, -1, +0]
  - [+0, +1, +0, +0, +0, +0]
  - [+0, -1, +0, +0, +0, +0]

  # ankle
  - [+0, +0, +0, +0, +0, +1]
  - [+0, +0, +0, +0, +0, -1]
  - [+0, +0, +1, +0, +0, +0]
  - [+0, +0, -1, +0, +0, +0]

  # tobillo + rodilla
  - [+0, +0, +0, +0, +1, -1]   # lean-forward correction (moderate)
  - [+0, +0, +0, +0, -1, +1]   # lean-back correction (strong)
  - [+0, +1, -1, +0, +0, +0]   # lean-forward correction (moderate)p
  - [+0, -1, +1, +0, +0, +0]   # lean-back correction (strong)

  - [+0, +0, +0, +0, +1, +1]
  - [+0, +0, +0, +0, -1, -1]
  - [+0, +1, +1, +0, +0, +0]
  - [+0, -1, -1, +0, +0, +0]
  
  # cadera + rodilla
  - [+0, +0, +0, +1, -1, +0]
  - [+0, +0, +0, -1, +1, +0]
  - [+1, -1, +0, +0, +0, +0]
  - [-1, +1, +0, +0, +0, +0]

  # COORDINACIÓN SIMÉTRICA

  # coordinación cadera
  - [+1, +0, +0, -1, +0, +0]
  - [-1, +0, +0, +1, +0, +0]

  # cadera + rodilla
  - [+1, -1, +0, -1, +1, +0]
  - [-1, +1, +0, +1, -1, +0]

  # cadera + rodilla
  - [+1, -1, +0, -1, +1, +0]
  - [-1, +1, +0, +1, -1, +0]

  # coordinación tobillos
  - [+0, +0, -1, +0, +0, +1]
  - [+0, +0, +1, +0, +0, -1]

  

train:
  total_steps: 30_000_000
  learning_starts: 2_000
  train_freq: 10 # 4
  batch_size: 64 # 32  # 64
  buffer_size: 200_000
  gamma: 0.99
  lr: 5.0e-5 # 1.0e-4 # 5.0e-5
  target_update_freq: 8000
  grad_clip_norm: 10.0

exploration:
  eps_start: 1.0
  eps_end: 0.05
  eps_decay_steps: 300_000

eval:
  # every_steps: 49999
  # every_steps: 19_999
  every_steps: 200_000
  episodes: 5

logging:
  render_every: 10
  run_dir: "runs"
  ckpt_dir: "checkpoints"
  log_every: 200_000

stabilizer:
  initial_intensity: 0.0 #10.5
  decay: 0.1
  ref_height: 0.95