seed: 0
device: "gpu"   # "cpu" si no tienes
# device: "cpu"   # "cpu" si no tienes

env:
  env_id: "Walker2d-v5"
  frame_stack: 4
  action_repeat: 1
  time_limit: 1000

  obs_h: 54
  obs_w: 54

  grayscale: false

  action_prototypes:

    # 0) noop
    - [+0, +0, +0, +0, +0, +0]

    # hip
    - [+0, +0, +0, +1, +0, +0]
    - [+0, +0, +0, -1, +0, +0]
    - [+1, +0, +0, +0, +0, +0]
    - [-1, +0, +0, +0, +0, +0]

    # knee
    - [+0, +0, +0, +0, +1, +0]
    - [+0, +0, +0, +0, -1, +0]
    - [+0, +1, +0, +0, +0, +0]
    - [+0, -1, +0, +0, +0, +0]

    # ankle
    - [+0, +0, +0, +0, +0, +1]
    - [+0, +0, +0, +0, +0, -1]
    - [+0, +0, +1, +0, +0, +0]
    - [+0, +0, -1, +0, +0, +0]

    # tobillo + rodilla
    - [+0, +0, +0, +0, +1, -1]   # lean-forward correction (moderate)
    - [+0, +0, +0, +0, -1, +1]   # lean-back correction (strong)
    - [+0, +1, -1, +0, +0, +0]   # lean-forward correction (moderate)p
    - [+0, -1, +1, +0, +0, +0]   # lean-back correction (strong)

    # - [+0, +0, +0, +0, +1, +1]
    # - [+0, +0, +0, +0, -1, -1]
    # - [+0, +1, +1, +0, +0, +0]
    # - [+0, -1, -1, +0, +0, +0]

    # cadera + rodilla
    - [+0, +0, +0, +1, -1, +0]
    - [+0, +0, +0, -1, +1, +0]
    - [+1, -1, +0, +0, +0, +0]
    - [-1, +1, +0, +0, +0, +0]

    # COORDINACIÓN SIMÉTRICA

    # coordinación cadera
    - [+1, +0, +0, -1, +0, +0]
    - [-1, +0, +0, +1, +0, +0]

    # cadera + rodilla
    - [+1, -1, +0, -1, +1, +0]
    - [-1, +1, +0, +1, -1, +0]

    # cadera + rodilla
    - [+1, -1, +0, -1, +1, +0]
    - [-1, +1, +0, +1, -1, +0]

    # coordinación tobillos
    - [+0, +0, -1, +0, +0, +1]
    - [+0, +0, +1, +0, +0, -1]

train:
  total_steps: 30_000_000
  learning_starts: 2_000
  train_freq: 10 # 4
  batch_size: 64 # 32  # 64
  buffer_size: 200_000
  gamma: 0.99
  lr: 5.0e-5 # 1.0e-4 # 5.0e-5
  target_update_freq: 8000
  grad_clip_norm: 10.0

# Rainbow-specific parameters
rainbow:
  # Distributional (C51)
  v_min: -5.0
  v_max: 150.0
  n_atoms: 51

  # N-step returns
  n_step: 3

  # Desactivamos noisy
  noisy_sigma0: 0.0

  # Prioritized replay
  prio_alpha: 0.6
  prio_beta_start: 0.4
  prio_beta_end: 1.0
  prio_beta_steps: 1_000_000
  prio_eps: 1.0e-6

eval:
  every_steps: 200_000
  episodes: 5

logging:
  render_every: 10
  run_dir: "runs"
  ckpt_dir: "checkpoints"
  log_every: 200_000
  live_frames: true
